// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC31FLHAEqQ9DQQDkNR2csEc-VUAesewpw',
    appId: '1:86698184446:web:2eb4ef5b8cb079978a5faf',
    messagingSenderId: '86698184446',
    projectId: 'chaty-fd549',
    authDomain: 'chaty-fd549.firebaseapp.com',
    storageBucket: 'chaty-fd549.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHhyJWbtbzHMIWz7mdp0GGx6nzdHSklig',
    appId: '1:86698184446:android:aaa3afeaa26e17e38a5faf',
    messagingSenderId: '86698184446',
    projectId: 'chaty-fd549',
    storageBucket: 'chaty-fd549.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnwHWAzLXugqUX8C-PnGrBSYWftB7X9M4',
    appId: '1:86698184446:ios:c862ec2a16a36adf8a5faf',
    messagingSenderId: '86698184446',
    projectId: 'chaty-fd549',
    storageBucket: 'chaty-fd549.appspot.com',
    iosClientId: '86698184446-b03hd67u6g42mjj60a2qg4ljtmfg27m3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnwHWAzLXugqUX8C-PnGrBSYWftB7X9M4',
    appId: '1:86698184446:ios:c862ec2a16a36adf8a5faf',
    messagingSenderId: '86698184446',
    projectId: 'chaty-fd549',
    storageBucket: 'chaty-fd549.appspot.com',
    iosClientId: '86698184446-b03hd67u6g42mjj60a2qg4ljtmfg27m3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chaty',
  );
}
